### ISSUE TITLE
Expand on more events than just "mousedown"

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-popover#19]
Currently, `juicy-popover` expands on `mousedown` event and collapses on `mousedown` outside.

Add a new attribute `expand-event` (and perhaps `collapse-event`?) that allows to specify alternative events, such as `mouseover` (`mouseenter`?)

cc @pilqerai

**Comment by warpech** [comment]
Initial implementation in branch [`center-and-hover-support`](https://github.com/Juicy/juicy-popover/compare/center-and-hover-support). 

@pileqrai decided to implement it as one attribute `expand-on`. I still think it should be two attributes: one for expanding and one for collapsing.

**Comment by PatrykSzwer** [comment]
Closing as done.
