### ISSUE TITLE
Clicking on the expandable should not collapse

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-popover#27]
Right now, when I click on the body of the expandable, unless on an `<input>` element, the expandable collapses. 

It should only collapse when clicked outside.

I propose to change https://github.com/Juicy/juicy-popover/blob/a62e431406f49c4797d3f45c8fefc81695c4154f/src/juicy-popover.html#L217-L219 to just:

```js
this.ignore = true;
```

**Comment by alshakero** [comment]
Closing as done in https://github.com/Juicy/juicy-popover/commit/4019346ba5acf7388c1dd8d25c7d8ffe482005a8
