### ISSUE TITLE
Unable to customize the expandable z-index

### ISSUE THREAD

**Issue by tekreme73** [Juicy/juicy-popover#29]
### Steps to reproduce
Use the element with a standard setup. The hard-coded z-index value for the expandable element can be too restrictive for some usage.

We may need to increase its value or decrease it.

### Expected result
z-index on the expandable CSS id can be customize to match the application context.

### Actual result
z-index is hard-coded to 999.

### Browsers affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

**Comment by alshakero** [comment]
Released 2.2.0 that fixes this https://github.com/Juicy/juicy-popover/releases/tag/2.2.0
