### ISSUE TITLE
Add some tests

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-popover#5]
It would be good to have a test suite, even basic one, like for other Juicy elements 
 - https://travis-ci.org/Juicy
 - https://github.com/Juicy/juicy-composition/tree/master/test

**Comment by warpech** [comment]
This element now has full test coverage added by @alshakero in https://github.com/Juicy/juicy-popover/pull/16.

Setting as “Finished” because it is:
- released (with release notes) https://github.com/Juicy/juicy-popover/releases/tag/2.0.0
