### ISSUE TITLE
Typo in the API

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-popover#9]
https://github.com/Juicy/juicy-popover/pull/4 introduced a typo in the API. Slot name `expendable` should be called `expandable`.

Should we fix or alias the API? I vote for aliasing, to avoid yet another breaking change. `juicy-popover` is used in many apps.

cc @tomalec

**Comment by tomalec** [comment]
I vote for aliasing, with deprecate warning.

**Comment by Mihaiii** [comment]
Closing as done.
